### ISSUE TITLE
syntax highlight doesn't handle string escapes

### ISSUE THREAD

**Issue by Shadlock0133** [seanahan5000/rpw-ext#3]
`!text "\""` should escape the inner double quote

**Comment by seanahan5000** [comment]
Thanks for the bug report.  I've got a large batch of changes going in within the next week and will get this fix in along with those.

**Comment by seanahan5000** [comment]
BTW, which syntax are you referring to?  Only ca65 appears to support escapes in strings but it doesn't have a .text op.

**Comment by Shadlock0133** [comment]
it's acme

**Comment by seanahan5000** [comment]
The extension has just been updated.  Let me know if you now see the expected behavior.

I ran tests on of the assembler executables and only CA65 appears to have the option to actually support string escapes.  The rest ignore them and will report an assembly error on "\"" because there's effectively an extra quote.  This includes ACME.  !text "\"" gives an assembly error.  The extension now matches the executable.

**Comment by Shadlock0133** [comment]
i've just tested with acme 0.97 (i'm using fork of 0.91 for my actual development) and both support `!text "\""` correctly.

the extension still misparses this case

**Comment by Shadlock0133** [comment]
the full file for test is
```
* = 0
!text "\""
```

**Comment by seanahan5000** [comment]
* = 0
!text "\""

sean@Seans-Mac acme % acme -V
This is ACME, release 0.96.4 ("Fenchurch"), 1 Feb 2019
  Platform independent version.
sean@Seans-Mac acme % acme test.asm
Error - File test.asm, line 2 (Zone <untitled>): Garbage data at end of statement.

**Comment by Shadlock0133** [comment]
huh, that's weird
i'm using extra/acme 0.97 from arch's repository

**Comment by Shadlock0133** [comment]
hmm, sourceforge repo has code for string escaping https://sourceforge.net/p/acme-crossass/code-0/HEAD/tree/trunk/src/input.c#l615

**Comment by seanahan5000** [comment]
Looks like string escapes were added in v.97.  From that same source file:
```
if (config.dialect < V0_97__BACKSLASH_ESCAPING)
```
I'll update to v.97 and make the extension match.  Thanks again for the help.  If you find other problems or have feature requests, please let me know!

**Comment by seanahan5000** [comment]
Version 1.3.1 has been published and should fix the problem

**Comment by Shadlock0133** [comment]
hmm, weird, i just updated to 1.3.1, and the highlight still doesn't seem correct
![image](https://github.com/user-attachments/assets/0786fd57-9356-4a2e-a981-dbfa3651cad7)

**Comment by seanahan5000** [comment]
<img width="491" alt="image" src="https://github.com/user-attachments/assets/0e3a02de-5bb1-4258-9bd7-754c510427e9">

**Comment by Shadlock0133** [comment]
huh, okay, it seems the problem is with some color themes, Rosé Pine and Witch Hazel have the bug, while default themes and Catppuccin looks fine. seems like a weird interaction between these themes and vscode's tokenizer. you can try finding the issue, but at least it works for me now :D thanks for fixes

**Comment by Shadlock0133** [comment]
actually, seems the different color themes just hide issue, the textmate syntax still thinks string extends after the literal
![image](https://github.com/user-attachments/assets/303240ed-7ef1-4715-bf58-024209c3592b)

**Comment by Shadlock0133** [comment]
here is correctly tokenized example
![image](https://github.com/user-attachments/assets/571c7810-9d35-4c2e-9d95-f9156dc2c475)

**Comment by seanahan5000** [comment]
Okay, there were some problems in rpw65.tmLanguage syntax definition file that are now fixed in v1.3.2.

**Comment by Shadlock0133** [comment]
yep, it's definitely fixed now, thanks!
